apiVersion: apps/v1
kind: Deployment
metadata:
  name: building-apps-deploy
  labels:
    app: kudeskills
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kudeskills
  template:
    metadata:
      labels:
        app: kudeskills
    spec:
      containers:
      - name: building-apps-container
        image: lander2k2/building-apps:0.1
